openapi: 3.1.0
info:
  title: Tina GPT Google Proxy
  version: 1.0.0
servers:
  - url: https://tina-gpt-proxy.onrender.com
paths:
  /calendar/events:
    get:
      operationId: getCalendarEvents
      summary: Get upcoming Google Calendar events
      responses:
        '200':
          description: A list of events
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    summary:
                      type: string
                    start:
                      type: string
                    end:
                      type: string
  /gmail/send:
    post:
      operationId: sendEmail
      summary: Send an email using Gmail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - to
                - subject
                - message
              properties:
                to:
                  type: string
                subject:
                  type: string
                message:
                  type: string
      responses:
        '200':
          description: Email sent
