openapi: 3.1.0
info:
  title: Tina GPT Google Proxy
  version: 1.1.0
servers:
  - url: https://tina-gpt-proxy.onrender.com
paths:
  /calendar/events:
    get:
      operationId: getCalendarEvents
      summary: Get upcoming Google Calendar events
      responses:
        '200':
          description: A list of events
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    summary:
                      type: string
                    start:
                      type: string
                    end:
                      type: string

  /gmail/send:
    post:
      operationId: sendEmail
      summary: Send an email using Gmail
      description: |
        Sends a **real email** through Gmail on behalf of the connected account.
        Requires `to`, `subject`, and `message`.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - to
                - subject
                - message
              properties:
                to:
                  type: string
                  description: Recipient email address
                subject:
                  type: string
                  description: Subject line of the email
                message:
                  type: string
                  description: Email body text
      responses:
        '200':
          description: Email sent successfully
        '400':
          description: Missing required fields
        '500':
          description: Failed to send email
